added new query for edx activity table
CDCgov/NEDSS-DataReporting pull request #113
Opened 2024-12-11 16:25 UTC by ndduc01

## Notes

Please include a summary of the change and which issue is fixed or which feature is added. 

## JIRA

- **Related story**: [Jira Ticket](url)

## Checklist

- [ ] PR focuses on a single story.
- [ ] New unit tests added and ensured they pass.
- [ ] Service has been tested in local and it works as expected.
- [ ] Documentation has been updated for this code change (if needed).
- [ ] Code follows the Java Coding Conventions (https://www.oracle.com/java/technologies/javase/codeconventions-programmingpractices.html).

## Types of changes

What types of changes does this PR introduces?

- [ ] Bugfix
- [ ] New feature
- [ ] Breaking change

## Testing

- [ ] Does this PR has >90% code coverage?
- [ ] Is the screenshot attached for code coverage?
- [ ] Does the `gradle build` pass in your local? 
- [ ] Is the `gradle build` logs attached?

2024-12-11 16:28 UTC, alog-enquizit approved these changes
lgtm 👍

2024-12-13 04:44 UTC, ndduc01 commented on liquibase-service/src/main/resources/db/rdb/routines/001-generate_data_for_data_sync_config-006.sql
> +-- Removing obsoleted query
ok, so I need to set this runOnChange flag to true?

2024-12-13 17:28 UTC, ndduc01 commented on liquibase-service/src/main/resources/db/rdb/routines/001-generate_data_for_data_sync_config-006.sql
> +-- Removing obsoleted query
added the runOnChange flag

2024-12-13 18:03 UTC, upasanapattnaik-eq requested changes
Consolidation discussion

2025-01-17 23:56 UTC, closed without merging